[package]
authors = ["Prasanna V. Loganathar <pvl@prasannavl.com>"]
name = "waldo"
version = "0.1.0"
[dependencies]
chrono = "0.4.0"
clap = "2.26.0"
kernel32-sys = "0.2.2"
ole32-sys = "0.2.0"
regex = "0.2.2"
user32-sys = "0.2.0"
winapi = "0.2.8"
